language: php

php:
  - hhvm
  - 7.0
  - 5.6
  - 5.3

matrix:
  fast_finish: true

before_script:
  - composer create-project wp-coding-standards/wpcs --no-dev

# Run PHP Code Sniffer to check WordPress coding standards
script:
  - wpcs/vendor/bin/phpcs -n --standard=./codesniffer.ruleset.xml --extensions=php --ignore=demo,tests,wpcs .

# Automatic deploy to wordpress.org when a new tag is created
deploy:
  on:
    branch: master
    tags: true
  provider: script
  script: ./scripts/wporg-deploy.sh
notifications:
  slack: elightup:dJunN1jYND443P6WizwZY8Kr
